title: Julia Cheat Sheet for Data Science
baseurl: ""
description: "Julia Cheat Sheet for Data Science"
github_username: kersulis
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: julia

t:
  en:
    name: "English"
    tagline: "Data science with"
    attribution-1: "Based on "
    attribution-2: "this intro to Julia"

altbaseurl: "http://jonaskersulis.com/julia-cheat-sheet"
